

import "./globals.css";
import HeartCursor from "../components/LoveTrail";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body      >
        <HeartCursor />
        {children}
      </body>
    </html>
  );
}
